version: '3.8'

services:
  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    depends_on:
      - php
    networks:
      - mock-case_selenium_network

  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/
    networks:
      - mock-case_selenium_network

  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    command:
      mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - mock-case_selenium_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=laravel_user
      - PMA_PASSWORD=laravel_pass
    depends_on:
      - mysql
    ports:
      - 8080:80
    networks:
      - mock-case_selenium_network
  
  mail:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
        - "1025:1025"
        - "8025:8025"
    networks:
      - mock-case_selenium_network
  
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"  
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
      - VNC_PASSWORD=secret
    networks:
      - mock-case_selenium_network

networks:
  mock-case_selenium_network:
    name: mock-case_selenium_network
    driver: bridge